language: java

jdk:
  - oraclejdk8

sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - metric_tests

script:
  - ./gradlew build --scan -s